spring.application.name=ai-chat-board
spring.datasource.url=jdbc:mysql://localhost:3306/ai_chat_board
spring.datasource.username=root
spring.datasource.password=TIGER

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080